name: publish to dockerhub

on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Release-client:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Docker login
        run: echo '${{ secrets.DOCKER_PWD }}' | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Docker Build
        run: docker build -t infinivis/infini-client:${GITHUB_REF#refs/tags/} --build-arg VERSION=${GITHUB_REF#refs/tags/} .

      - name: Docker tag
        run: docker tag infinivis/infini-client:${GITHUB_REF#refs/tags/} infinivis/infini-client:latest

      - name: Docker Push version
        run: docker push infinivis/infini-client:${GITHUB_REF#refs/tags/}

      - name: Docker Push lastest
        run: docker push infinivis/infini-client

  Release-server:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Docker login
        run: echo '${{ secrets.DOCKER_PWD }}' | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Docker Build
        run: docker build -t infinivis/infini-server:${GITHUB_REF#refs/tags/} --build-arg VERSION=${GITHUB_REF#refs/tags/} .

      - name: Docker tag
        run: docker tag infinivis/infini-server:${GITHUB_REF#refs/tags/} infinivis/infini-server:latest

      - name: Docker Push version
        run: docker push infinivis/infini-server:${GITHUB_REF#refs/tags/}

      - name: Docker Push lastest
        run: docker push infinivis/infini-server
